<?php
    /**
     * PHY
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@kinopio.net so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY
     * @copyright Copyright (c) 2011 KinopioNet (http://www.kinopio.net/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy
     * 
     * @var $this \PHY\View\Block
     * @var $link array
     * @see \PHY\View\Header\Menu
     */
?>
<div class="header-menu">
    <ul><?php
    $tag = $this->tag();
    foreach ($links as $link):
        echo $tag->li(
            $tag->url($link['title'], $this->url($link['url']), array_key_exists('attributes', $link) && array_key_exists('a', $link['attributes'])?$link['attributes']['a']:NULL), array_key_exists('attributes', $link) && array_key_exists('li', $link['attributes'])?$link['attributes']['li']:NULL
        );
    endforeach;
?></ul>
</div>