<?php
    /**
     * PHY
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@kinopio.net so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY
     * @copyright Copyright (c) 2011 KinopioNet (http://www.kinopio.net/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy
     * 
     * @var $this \PHY\View\Block
     * @var $email string
     */
?>
<div class="login">
    <h1>Login<a class="login-button" href="<?=$this->url('register')?>">Register</a></h1>
    <form action="<?=$this->url('login')?>" method="post">
        <?=$this->child('error')?>
        <fieldset class="text">
            <input id="login-email" autosave="yes" class="inp-text large" name="email" placeholder="Email" type="email" value="<?=$this->clean(isset($email)?$email:NULL)?>" />
            <input id="login-password" class="inp-text large" placeholder="Password" name="password" type="password" />
        </fieldset>
        <fieldset class="submit">
            <button><span><span>Login</span></span></button>
        </fieldset>
    </form>
</div>
<p><a href="<?=$this->url('forgot')?>">Forgot your password?</a></p>