<?php
    /**
     * PHY
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@kinopio.net so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY
     * @copyright Copyright (c) 2011 KinopioNet (http://www.kinopio.net/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy
     * 
     * @var $this \PHY\View\Block
     * @var $js array
     * @var $css array
     * @see \PHY\View\Head
     */
?>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
<title><?=\PHY\Registry::get('site')->title?></title>
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<script type="text/javascript">if(window.location.hash.toString().match('!')){var url=window.location.hash.toString().split('!');window.location=url[1];}</script>
<?php foreach($js as $file):?>
<script type="text/javascript" src="<?=$file?>"></script>
<?php endforeach?>
<script type="text/javascript">$.user={xsrf_id:'<?=\PHY\Cookie::get('xsrf_id')?>',id:'<?=\PHY\Registry::get('user/session')->id?>'};</script>
<?php foreach($css as $file):?>
<link rel="stylesheet" href="<?=$file?>" type="text/css" />
<?php endforeach?>