<?php
    /**
     * PHY
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@kinopio.net so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY
     * @copyright Copyright (c) 2011 KinopioNet (http://www.kinopio.net/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy
     *
     * @var $this \PHY\View\Block
     */
?>
<!DOCTYPE html>
<html>
    <head><?=$this->child('head');?></head>
    <body class="two-column">>
        <div id="container">
            <?=$this->child('header')?>
            <section id="main">
                <div id="wrapper">
                    <div id="col-2"><?=$this->child('sidebar')?></div>
                    <div id="col-1">
                        <div id="content"><?=$this->child('content')?></div>
                    </div>
                </div>
            </section>
            <?=$this->child('footer')?>
        </div>
    </body>
</html>